####################################################################################################
# Mesh
ndims = 2
n_cells_max = 50000
coordinates_min = [-2, -2]
coordinates_max =  [2, 2]
initial_refinement_level = 5
#periodicity = true
 refinement_patches = [
   {type = "box", coordinates_min = [-1.3, -1.3], coordinates_max = [-0.8, -0.8]},
   {type = "box", coordinates_min = [-1.1, -1.1], coordinates_max = [-0.9, -0.9]},
   {type = "box", coordinates_min = [0.8, 0.8], coordinates_max = [1.2, 1.2]},
   #{type = "box", coordinates_min = [0.9, 0.9], coordinates_max = [1.1, 1.1]},
 ]