####################################################################################################
# Mesh
ndims = 2
n_cells_max = 50000
coordinates_min = [-1, -1]
coordinates_max =  [1, 1]
initial_refinement_level = 5
periodicity = true
 refinement_patches = [
   {type = "box", coordinates_min = [-1.0, -1.0], coordinates_max = [-0.5, -0.5]},
   {type = "box", coordinates_min = [-0.5, -0.5], coordinates_max = [0.0, 0.0]},
   {type = "box", coordinates_min = [0.0, 0.0], coordinates_max = [0.5, 0.5]},
   {type = "box", coordinates_min = [0.5, 0.5], coordinates_max = [1.0, 1.0]},
   {type = "box", coordinates_min = [-1.0, -1.0], coordinates_max = [-0.75, -0.75]},#
   {type = "box", coordinates_min = [-0.75, -0.75], coordinates_max = [-0.5, -0.5]},
   {type = "box", coordinates_min = [-0.5, -0.5], coordinates_max = [-0.25, -0.25]},#
   {type = "box", coordinates_min = [-0.25, -0.25], coordinates_max = [0.0, 0.0]},
   {type = "box", coordinates_min = [0.0, 0.0], coordinates_max = [0.25, 0.25]},#
   {type = "box", coordinates_min = [0.25, 0.25], coordinates_max = [0.5, 0.5]},
   {type = "box", coordinates_min = [0.5, 0.5], coordinates_max = [0.75, 0.75]},
   {type = "box", coordinates_min = [0.75, 0.75], coordinates_max = [1.0, 1.0]},
 ]