ndims = 1

# Mesh
n_cells_max = 30000
coordinates_min = [-1]
coordinates_max =  [1]
initial_refinement_level = 5
#refinement_patches = [
#   {type = "box", coordinates_min = [-0.5], coordinates_max = [0.5]},
#   {type = "box", coordinates_min = [-0.1], coordinates_max = [0.1]},
 #]